// types.ts

export interface Activity {
  time: string;
  description: string;
}

export interface DayItinerary {
  day: number;
  theme: string;
  activities: Activity[];
}

// Defines user input for generating an itinerary
export interface TravelPreferences {
  destination: string;
  duration: number; // in days
  interests: string;
  // travelers: number; // Removed
  budget: number;
  currency: string;
  latitude?: number; // Optional, if geolocation is enabled
  longitude?: number; // Optional, if geolocation is enabled
}

// The structured itinerary generated by the AI
export interface GeneratedItinerary {
  destination: string;
  duration: number; // in days
  overview: string;
  itinerary: DayItinerary[];
  packingSuggestions: string[];
  notes: string;
  budgetSummary?: string; // Optional: AI's summary/analysis of the budget
}

// The complete result returned by the itinerary generation service
export interface ItineraryResult {
  itineraryData: GeneratedItinerary;
  sourceUrls: { uri: string; title?: string }[];
}

// Status of geolocation retrieval
export interface GeolocationStatus {
  latitude: number | null;
  longitude: number | null;
  isGettingLocation: boolean;
  error: string | null;
}